name: Docker Hub auto push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: make ci

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to Dockerhub
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile.production
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-project-74:latest
